apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol
spec:
  capacity:
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  storageClassName: fast
  awsElasticBlockStore: 
    fsType: ext4
    volumeID: vol-01ceaf27ff224334b